name: euphoniaaireviewer_admin
description: Manage your Euphonia-AI-Reviewer projects.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2  # Use with the CupertinoIcons class for iOS style icons.
  flutter_card_swiper: ^7.0.0
  firebase_ui_shared : ^1.4.1 #https://github.com/firebase/FirebaseUI-Flutter/issues/140#issuecomment-1763243442
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_ui_auth: ^1.14.0
  fftea: ^1.5.0
  image: ^4.1.6
  wav: ^1.3.0
  audioplayers: ^6.0.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  cached_network_image: ^3.3.1
  cloud_functions: ^4.6.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  file_picker: ^8.0.3
  csv: ^6.0.0
  just_audio: ^0.9.36
  archive: ^3.4.10
  percent_indicator: ^4.2.3
  path_provider: ^2.1.2
  dio: ^5.4.1

# dependency_overrides:
#   firebase_auth: "4.12.0" #https://stackoverflow.com/questions/77468892/error-authprovider-is-imported-from-both


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/AppIcon.jpg